config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "application#root"

  resources :companies do
    resources :users do
      resources :reimbursement_claims
    end
  end
end

app/models/reimbursement_claim.rb
class ReimbursementClaim < ApplicationRecord
  belongs_to :user
  has_one_attached :receipt # Use ActiveStorage for file uploads

  # Validations
  validates :purpose, presence: true, length: { minimum: 4 }
  validates :amount, presence: true, numericality: { greater_than: 0.01 }
end

app/controllers/reimbursement_claims_controller.rb
class ReimbursementClaimsController < ApplicationController
    before_action :set_company
    before_action :set_employee
    before_action :set_reimbursement_claim, only: [:show, :edit, :update, :destroy]
  
    def index
      @reimbursement_claims = @employee.reimbursement_claims.page(params[:page] || 1).per(10)
    end
  
    def show
      respond_to do |format|
        format.js { render partial: 'reimbursement_claims/partials/show' }
      end
    end
  
    def new
      @reimbursement_claim = @employee.reimbursement_claims.build
      respond_to do |format|
        format.js { render partial: 'reimbursement_claims/partials/new' }
      end
    end
  
    def create
      @reimbursement_claim = @employee.reimbursement_claims.build(reimbursement_claim_params)
      if @reimbursement_claim.save
        redirect_to request.referer, notice: 'Reimbursement claim was successfully created.'
      else
        render :new
      end
    end
  
    def edit
      respond_to do |format|
        format.js { render partial: 'reimbursement_claims/partials/edit' }
      end
    end
  
    def update
      if @reimbursement_claim.update(reimbursement_claim_params)
        redirect_to request.referer || company_user_reimbursement_claims_path(@company, @user), notice: 'Reimbursement claim was successfully updated.'
      else
        respond_to do |format|
          format.js { render partial: 'reimbursement_claims/partials/edit' }
        end
      end
    end
  
    def destroy
      @reimbursement_claim.destroy
      redirect_to company_user_reimbursement_claims_path(@company, @employee), notice: 'Reimbursement claim was successfully destroyed.'
    end
  
    private
  
    def set_company
      @company = Company.find(params[:company_id])
    end
  
    def set_employee
      @employee = @company.users.find(params[:user_id])
    end
  
    def set_reimbursement_claim
      @reimbursement_claim = @employee.reimbursement_claims.find(params[:id])
    end
  
    def reimbursement_claim_params
      params.require(:reimbursement_claim).permit(:purpose, :amount, :date_of_expenditure, :receipt)
    end
end
  

app/views/reimbursement_claims/index.html.erb
<div class="container mt-4">
  <h1 class="text-center text-primary mb-4">Reimbursement Claims for <%= @employee.fname %> <%= @employee.lname %></h1>
  <div class="text-end"><a href="#" onclick="openGlobalModal('<%= new_company_user_reimbursement_claim_path(@company, @employee) %>', 'New Reimbursement Claim')" class='btn btn-primary mb-3'>New Reimbursement Claim</a></div>

  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Purpose</th>
        <th>Amount</th>
        <th>Date of Expenditure</th>
        <th>Receipt</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @reimbursement_claims.each do |claim| %>
        <tr>
          <td><a href="#" onclick="openGlobalModal('<%= company_user_reimbursement_claim_path(@company, @employee, claim)  %>', 'Reimbursement Claim Details')"><%= claim.purpose %></a></td>
          <td><%= number_to_currency(claim.amount) %></td>
          <td><%= claim.date_of_expenditure %></td>
          <td>
            <% if claim.receipt.attached? %>
              <%= link_to 'View Receipt', rails_blob_path(claim.receipt, disposition: 'inline'), target: '_blank' %>
            <% else %>
              No receipt
            <% end %>
          </td>
          <td>
            <a href="#" onclick="openGlobalModal('<%= edit_company_user_reimbursement_claim_path(@company, @employee, claim) %>', 'Edit Reimbursement Claim')" class='btn btn-secondary btn-sm'>Edit</a>
            <a href="<%= company_user_reimbursement_claim_path(@company, @employee, claim) %>" class="delete-link btn btn-danger btn-sm ml-2" data-url="<%= company_user_reimbursement_claim_path(@company, @employee, claim) %>" data-method="delete">Delete</a>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% paginate @reimbursement_claims %>
  <div class='text-end'><%= link_to 'Back to Users', company_path(@company), class: 'btn btn-secondary mt-3' %></div>
</div>


<script>
  const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

  document.querySelectorAll(".delete-link").forEach(link => {
    link.addEventListener("click", function(event) {
      event.preventDefault();
      const url = link.getAttribute("data-url");

      if (confirm("Are you sure?")) {
        fetch(url, {
          method: 'DELETE',
          headers: {
            'X-CSRF-Token': csrfToken,
            'Accept': 'application/json'
          }
        })
        .then(response => {
          window.location.reload(); // Refresh the page on success
        })
        .catch(() => alert("An error occurred. Please try again."));
      }
    });
  });
</script>